### ISSUE TITLE
Finding Nearby Devices without pairing approval

### ISSUE THREAD

**Issue by fresh83** [indragiek/INDANCSClient#3]
Were looking to create a service that finds nearby users using bt autonomously , your lib looks on the surface like something that might solve our problem , is it possible to use this lib to find nearby devices ( all we need is a single unique identifier )

**Comment by indragiek** [comment]
You can't discover devices without having software running on the device to advertise it. See `INDANCSServer` for how you advertise a Bluetooth service. And it's not possible to read any data from the device aside from the publicly advertised name without pairing with it.

**Comment by fresh83** [comment]
...so you say

**Comment by fresh83** [comment]
according to you, will see about that

Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----
